baseURL = "http://outme.hervedarritchon.fr"
languageCode = 'en-us'
defaultContentLanguage = "en"
title = "Once Upon a Time in Middle-Earth"
theme = "zzo"
enableRobotsTXT = true

defaultContentLanguageInSubdir = true
hasCJKLanguage = false

summaryLength = 70
buildFuture = true

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

enableGitInfo = false
googleAnalytics = "UA-214081111-2"

[taxonomies]
tag = "tags"
category = 'categories'
series = 'series'
tutorials = 'tutorials'

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
homeMetaContent = "A blog about The One Ring TTRPG and Foundry VTT."
dateFormat = "2 Jan 2006"
navTitleLink = "/"

sectionPagesMenu = "main"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true