[[main]]
  identifier = "the-one-ring"
  name = "The One Ring"
  url = "the-one-ring"
  weight = 1

[[main]]
  identifier = "tor2e"
  name = "Tor2e System"
  url = "tor2e-system"
  weight = 2

[[main]]
  identifier = "foundryvtt"
  name = "Foundry VTT"
  url = "foundryvtt"
  weight = 3

[[main]]
  identifier = "resources"
  name = "Resources"
  url = "resources"
  weight = 4

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 5