[[main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 1

[[main]]
  identifier = "the-one-ring"
  name = "L'Anneau Unique"
  url = "/tags/the-one-ring"
  weight = 2

[[main]]
  identifier = "tor2e"
  name = "Système Tor2e"
  url = "/tags/tor2e-system"
  weight = 3

[[main]]
  identifier = "foundryvtt"
  name = "Foundry VTT"
  url = "/tags/foundryvtt"
  weight = 4