[[main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 1

[[main]]
  identifier = "the-one-ring"
  name = "The One Ring"
  url = "/tags/the-one-ring"
  weight = 10

[[main]]
  identifier = "tor2e"
  name = "Tor2e System"
  url = "/tags/tor2e-system"
  weight = 20

[[main]]
  identifier = "foundryvtt"
  name = "Foundry VTT"
  url = "/tags/foundryvtt"
  weight = 30

#[[main]]
#  identifier = "resources"
#  name = "Resources"
#  url = "resources"
#  weight = 40
#
#[[main]]
#  identifier = "archive"
#  name = "Archive"
#  url = "archive"
#  weight = 50