[[main]]
  identifier = "the-one-ring"
  name = "L'Anneau Unique"
  url = "the-one-ring"
  weight = 1

[[main]]
  identifier = "tor2e"
  name = "Système Tor2e"
  url = "tor2e-system"
  weight = 2

[[main]]
  identifier = "foundryvtt"
  name = "Foundry VTT"
  url = "foundryvtt"
  weight = 3

[[main]]
  identifier = "resources"
  name = "Ressources"
  url = "resources"
  weight = 4
  
[[main]]
  identifier = "archive"
  name = "Archives"
  url = "archive"
  weight = 5